{{- if .Values.webhook.enabled }}
{{- $ca := genCA "harbor-internal-ca" 365 }}
{{- $coreCN := include "common.names.fullname"  . }}

{{- $coreCrt := genSignedCert $coreCN (list "127.0.0.1") (list "localhost" $coreCN) 365 $ca }}

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.csi.vsphere.vmware.com
webhooks:
  - name: validation.csi.vsphere.vmware.com
    clientConfig:
      service:
        name: vsphere-webhook-svc
        namespace: kube-system
        path: "/validate"
      caBundle: {{ $ca.Cert | b64enc | quote }}
    rules:
      - apiGroups:   ["storage.k8s.io"]
        apiVersions: ["v1", "v1beta1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["storageclasses"]
    sideEffects: None
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-webhook-certs
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "common.names.fullname" . }}-webhook
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  key.pem:  {{ $coreCrt.Key  | quote }}
  cert.pem: {{ $coreCrt.Cert | quote }}
  webhook.config: |
    [WebHookConfig]
    port = "8443"
    cert-file = "/etc/webhook/cert.pem"
    key-file = "/etc/webhook/key.pem"
{{- end }}